import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
	contentCalendar: {
		dashboardLabel: 'Calendar',
		headline: 'Content calendar',
		previousMonth: 'Previous month',
		nextMonth: 'Next month',
		previousWeek: 'Previous week',
		nextWeek: 'Next week',
		previousDay: 'Previous day',
		nextDay: 'Next day',
		today: 'Today',
		refresh: 'Refresh',
		refreshLabel: 'Reload the dates in view from the server',
		loading: 'Loading calendar…',
		viewSwitcherLabel: 'Calendar view',
		viewMonth: 'Month',
		viewWeek: 'Week',
		viewDay: 'Day',
		viewList: 'List',
		emptyMonth: 'Nothing was created, scheduled or deleted in %0%.',
		emptyWeek: 'Nothing was created, scheduled or deleted during %0%.',
		emptyDay: 'Nothing was created, scheduled or deleted on %0%.',
		emptyFiltered: 'Everything in view is hidden by the filters.',
		showAll: 'Show all',
		truncated: 'There are more items than can be shown. Some entries are omitted.',
		loadFailed: 'The calendar could not be loaded.',
		filters: 'Show or hide items by state',
		filterHide: 'Hide from calendar',
		filterShow: 'Show in calendar',
		filterButtonLabel: '%0%: %1%',
		itemCountOne: '%0% item',
		itemCountOther: '%0% items',
		tileDraft: 'Draft',
		tilePublished: 'Published',
		tileScheduled: 'Scheduled to publish',
		tileUnpublish: 'Scheduled to unpublish',
		tileDeleted: 'Deleted',
		tileTextDraft: '%0% created, but not published yet.',
		tileTextPublished: '%0% created and live on the website.',
		tileTextScheduled: '%0% will go live automatically.',
		tileTextUnpublish: '%0% will be taken offline automatically.',
		tileTextDeleted: '%0% moved to the recycle bin.',
		kindCreated: 'Created (draft)',
		kindPublished: 'Created (published)',
		kindScheduled: 'Publish at',
		kindUnpublish: 'Unpublish at',
		kindDeleted: 'Deleted',
		draftCount: '%0% created (draft)',
		publishedCount: '%0% created (published)',
		scheduledCount: '%0% scheduled to publish',
		unpublishCount: '%0% scheduled to unpublish',
		deletedCount: '%0% deleted',
		moreButton: '+%0%',
		moreText: '+%0% more',
		moreLinkHint: 'Show %0% more items',
		moreLabel: 'Show all %0% items for %1%',
		dayLabel: '%0%: %1% created, %2% scheduled to publish, %3% scheduled to unpublish, %4% deleted',
		hoverOpen: 'Click to open in the editor',
		dayOverflowHeadline: 'Content for %0%',
		columnName: 'Name',
		columnDocumentType: 'Document type',
		columnDate: 'Date and time',
		columnState: 'State',
		columnCulture: 'Culture',
		columnActions: 'Actions',
		open: 'Open',
		openItem: 'Open %0%',
		close: 'Close',
		sortBy: 'Sort by %0%',
		scheduledPendingNote:
			'Schedules (publish and unpublish) are removed once they have run, so past months only show created items. Deleted items are shown on the day they were moved to the recycle bin, until they are restored or permanently deleted.',
		collectionNote:
			'Shows the child items of this page only. Schedules (publish and unpublish) are removed once they have run, so past months only show created items. Deleted child items are shown on the day they were moved to the recycle bin, until they are restored or permanently deleted.',
	},
} satisfies UmbLocalizationDictionary;
