// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ContentCalendarDayModel = {
    date: string;
    createdCount: number;
    scheduledCount: number;
    scheduledUnpublishCount: number;
    deletedCount: number;
    entries: Array<ContentCalendarEntryModel>;
};

export type ContentCalendarDocumentTypeModel = {
    alias: string;
    name: string;
    icon: string;
};

export type ContentCalendarEntryKindModel = 'Created' | 'ScheduledPublish' | 'Deleted' | 'ScheduledUnpublish';

export type ContentCalendarEntryModel = {
    id: string;
    name: string;
    documentType: ContentCalendarDocumentTypeModel;
    culture?: string | null;
    date: string;
    kind: ContentCalendarEntryKindModel;
    isPublished: boolean;
};

export type ContentCalendarMonthResponseModel = {
    year: number;
    month: number;
    monthKey: string;
    timeZone: string;
    totalCreated: number;
    totalScheduled: number;
    totalScheduledUnpublish: number;
    totalDeleted: number;
    isTruncated: boolean;
    days: Array<ContentCalendarDayModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type GetMonthData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        month: number;
        timeZone?: string;
        parentKey?: string;
    };
    url: '/umbraco/management/api/v1/content-calendar/month';
};

export type GetMonthErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetMonthError = GetMonthErrors[keyof GetMonthErrors];

export type GetMonthResponses = {
    /**
     * OK
     */
    200: ContentCalendarMonthResponseModel;
};

export type GetMonthResponse = GetMonthResponses[keyof GetMonthResponses];
